In [10]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

In [11]:
df=pd.read_csv("insurance.csv")
df.head()

   age  sex     bmi  children  smoker  region      charges  insuranceclaim
0   19    0  27.900         0       1       3  16884.92400               1
1   18    1  33.770         1       0       2   1725.55230               1
2   28    1  33.000         3       0       2   4449.46200               0
3   33    1  22.705         0       0       1  21984.47061               0
4   32    1  28.880         0       0       1   3866.85520               1

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             1338 non-null   int64
 1   sex             1338 non-null   int64
 2   bmi             1338 non-null   float64
 3   children        1338 non-null   int64
 4   smoker          1338 non-null   int64
 5   region          1338 non-null   int64
 6   charges         1338 non-null   float64
 7   insuranceclaim  1338 non-null   int64
dtypes: float64(2), int64(6)
memory usage: 83.8 KB

In [13]:
features=df.drop("insuranceclaim",axis=1)
target=df["insuranceclaim"]

In [14]:
len(features.columns)

7

In [15]:
df["insuranceclaim"].value_counts()

insuranceclaim
1    783
0    555
Name: count, dtype: int64

In [16]:
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
features.iloc[:]=ss.fit_transform(features.iloc[:])
features

           age       sex       bmi  children    smoker    region   charges
0    -1.438764 -1.010519 -0.453320 -0.908614  1.970587  1.343905  0.298584
1    -1.509965  0.989591  0.509621 -0.078767 -0.507463  0.438495 -0.953689
2    -0.797954  0.989591  0.383307  1.580926 -0.507463  0.438495 -0.728675
3    -0.441948  0.989591 -1.305531 -0.908614 -0.507463 -0.466915  0.719843
4    -0.513149  0.989591 -0.292556 -0.908614 -0.507463 -0.466915 -0.776802
...        ...       ...       ...       ...       ...       ...       ...
1333  0.768473  0.989591  0.050297  1.580926 -0.507463 -0.466915 -0.220551
1334 -1.509965 -1.010519  0.206139 -0.908614 -0.507463 -1.372326 -0.914002
1335 -1.509965 -1.010519  1.014878 -0.908614 -0.507463  0.438495 -0.961596
1336 -1.296362 -1.010519 -0.797813 -0.908614 -0.507463  1.343905 -0.930362
1337  1.551686 -1.010519 -0.261388 -0.908614  1.970587 -0.466915  1.311053

[1338 rows x 7 columns]

In [17]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(features,target,random_state=0,test_size=0.2,stratify=target)
print(xtrain.shape,ytrain.shape)
print(xtest.shape,ytest.shape)

(1070, 7) (1070,)
(268, 7) (268,)

In [18]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [19]:
def mymodel(model):
    model.fit(xtrain,ytrain)
    ypred=model.predict(xtest)
    #Overfitting - underfitting check
    print(f"Training score : {model.score(xtrain,ytrain)}")
    print(f"Testing score : {model.score(xtest,ytest)}")
    c=pd.DataFrame(confusion_matrix(ypred,ytest),
                  index=["Not Claimed","Claimed"],
                  columns=["Not Claimed","Claimed"])
    print("Confusion Matrix : \n",c)
    print("Classification Report : \n",classification_report(ytest,ypred))
    return model

In [20]:
mymodel(LogisticRegression())

Training score : 0.8822429906542056
Testing score : 0.8694029850746269
Confusion Matrix :
              Not Claimed  Claimed
Not Claimed           90       14
Claimed               21      143
Classification Report :
               precision    recall  f1-score   support

           0       0.87      0.81      0.84       111
           1       0.87      0.91      0.89       157

    accuracy                           0.87       268
   macro avg       0.87      0.86      0.86       268
weighted avg       0.87      0.87      0.87       268

LogisticRegression()

In [21]:
# feature extraction
from sklearn.decomposition import PCA
pca = PCA(n_components=4)
xtrain_pca=pca.fit_transform(xtrain)
xtest_pca=pca.transform(xtest)

In [22]:
xtrain_pca

array([[-0.33827757,  0.26000189, -0.12394413, -0.32145453],
       [-1.63961079, -0.00680897, -0.93525264, -0.7917976 ],
       [ 2.35017909, -0.78750418,  0.86620435, -1.79513106],
       ...,
       [-1.51732909, -0.19926514, -0.0748717 ,  0.57726203],
       [ 2.48916461, -0.61003968, -1.27243752,  1.24172679],
       [-0.44752287, -1.78041131,  0.90012139,  0.12090465]])

In [25]:
def mymodel(model):
    model.fit(xtrain_pca,ytrain)
    ypred=model.predict(xtest_pca)
    #Overfitting - underfitting check
    print(f"Training score : {model.score(xtrain_pca,ytrain)}")
    print(f"Testing score : {model.score(xtest_pca,ytest)}")
    c=pd.DataFrame(confusion_matrix(ypred,ytest),
                  index=["Not Claimed","Claimed"],
                  columns=["Not Claimed","Claimed"])
    print("Confusion Matrix : \n",c)
    print("Classification Report : \n",classification_report(ytest,ypred))
    return model

In [26]:
mymodel(LogisticRegression())

Training score : 0.814018691588785
Testing score : 0.7798507462686567
Confusion Matrix :
              Not Claimed  Claimed
Not Claimed           72       20
Claimed               39      137
Classification Report :
               precision    recall  f1-score   support

           0       0.78      0.65      0.71       111
           1       0.78      0.87      0.82       157

    accuracy                           0.78       268
   macro avg       0.78      0.76      0.77       268
weighted avg       0.78      0.78      0.78       268

LogisticRegression()